"""Pydantic schemas package."""

from .data import (
    StockInfo,
    StockListResponse,
    OHLCVData,
    StockDataResponse,
    FeatureData,
    FeaturesResponse,
    FetchDataRequest,
    FetchDataResponse,
)
from .models import (
    ModelType,
    ModelStatus,
    PhysicsParameters,
    ModelInfo,
    ModelListResponse,
    ModelDetailResponse,
    ModelWeightsInfo,
    ModelComparisonItem,
    ModelComparisonResponse,
)
from .predictions import (
    UncertaintyMethod,
    SignalAction,
    PredictionRequest,
    PredictionInterval,
    PredictionResult,
    PredictionResponse,
    BatchPredictionRequest,
    BatchPredictionResponse,
    PredictionHistoryItem,
    PredictionHistoryResponse,
    LatestPredictionResponse,
)
from .training import (
    TrainingStatus,
    TrainingRequest,
    TrainingJobInfo,
    TrainingStartResponse,
    TrainingStopResponse,
    TrainingStatusResponse,
    EpochMetrics,
    TrainingHistoryResponse,
    TrainingRunListResponse,
)
from .backtesting import (
    PositionSizingMethod,
    TradeAction,
    BacktestRequest,
    Trade,
    PortfolioSnapshot,
    DrawdownInfo,
    BacktestResults,
    BacktestResponse,
    BacktestSummary,
    BacktestListResponse,
    TradeHistoryResponse,
)
from .metrics import (
    MLMetrics,
    FinancialMetrics,
    PhysicsMetrics,
    ModelMetricsResponse,
    MetricsComparisonResponse,
    FinancialMetricsRequest,
    FinancialMetricsResponse,
)
from .monte_carlo import (
    MonteCarloRequest,
    ConfidenceInterval,
    SimulationPath,
    DistributionStats,
    MonteCarloResults,
    MonteCarloResponse,
    MonteCarloSummary,
    MonteCarloListResponse,
)
from .trading import (
    TradingMode,
    OrderType,
    OrderStatus,
    AlertSeverity,
    AlertType,
    PositionSizingMethod as TradingPositionSizingMethod,
    AgentConfigRequest,
    ManualOrderRequest,
    ClosePositionRequest,
    Signal,
    Position,
    Trade as TradingTrade,
    Order,
    Alert,
    PortfolioAllocation,
    ConfidenceHistoryPoint,
    PerformanceMetrics,
    MarketData,
    AgentStatus,
    AgentStartResponse,
    AgentStopResponse,
    TradeHistoryResponse as TradingTradeHistoryResponse,
    OrderHistoryResponse,
    AlertHistoryResponse,
    PortfolioHistoryPoint,
    PortfolioHistoryResponse,
    RiskMetrics,
    RiskMetricsResponse,
)

__all__ = [
    # Data
    "StockInfo",
    "StockListResponse",
    "OHLCVData",
    "StockDataResponse",
    "FeatureData",
    "FeaturesResponse",
    "FetchDataRequest",
    "FetchDataResponse",
    # Models
    "ModelType",
    "ModelStatus",
    "PhysicsParameters",
    "ModelInfo",
    "ModelListResponse",
    "ModelDetailResponse",
    "ModelWeightsInfo",
    "ModelComparisonItem",
    "ModelComparisonResponse",
    # Predictions
    "UncertaintyMethod",
    "SignalAction",
    "PredictionRequest",
    "PredictionInterval",
    "PredictionResult",
    "PredictionResponse",
    "BatchPredictionRequest",
    "BatchPredictionResponse",
    "PredictionHistoryItem",
    "PredictionHistoryResponse",
    "LatestPredictionResponse",
    # Training
    "TrainingStatus",
    "TrainingRequest",
    "TrainingJobInfo",
    "TrainingStartResponse",
    "TrainingStopResponse",
    "TrainingStatusResponse",
    "EpochMetrics",
    "TrainingHistoryResponse",
    "TrainingRunListResponse",
    # Backtesting
    "PositionSizingMethod",
    "TradeAction",
    "BacktestRequest",
    "Trade",
    "PortfolioSnapshot",
    "DrawdownInfo",
    "BacktestResults",
    "BacktestResponse",
    "BacktestSummary",
    "BacktestListResponse",
    "TradeHistoryResponse",
    # Metrics
    "MLMetrics",
    "FinancialMetrics",
    "PhysicsMetrics",
    "ModelMetricsResponse",
    "MetricsComparisonResponse",
    "FinancialMetricsRequest",
    "FinancialMetricsResponse",
    # Monte Carlo
    "MonteCarloRequest",
    "ConfidenceInterval",
    "SimulationPath",
    "DistributionStats",
    "MonteCarloResults",
    "MonteCarloResponse",
    "MonteCarloSummary",
    "MonteCarloListResponse",
    # Trading
    "TradingMode",
    "OrderType",
    "OrderStatus",
    "AlertSeverity",
    "AlertType",
    "TradingPositionSizingMethod",
    "AgentConfigRequest",
    "ManualOrderRequest",
    "ClosePositionRequest",
    "Signal",
    "Position",
    "TradingTrade",
    "Order",
    "Alert",
    "PortfolioAllocation",
    "ConfidenceHistoryPoint",
    "PerformanceMetrics",
    "MarketData",
    "AgentStatus",
    "AgentStartResponse",
    "AgentStopResponse",
    "TradingTradeHistoryResponse",
    "OrderHistoryResponse",
    "AlertHistoryResponse",
    "PortfolioHistoryPoint",
    "PortfolioHistoryResponse",
    "RiskMetrics",
    "RiskMetricsResponse",
]
